### ISSUE TITLE
Filter by less popular Tags which are not visible on the side filter

### ISSUE THREAD

**Issue by marisveide** [watch-devtube/web#38] opened 2018-06-28 05:15 UTC
I should be able to expand the Tags list to see more Tags than just top ones, so that I can find the less popular tags like”Ruby”.

Workaround is to search video by text and then click on the Tag, and then clear the search text.

Or maybe the Search could suggest filtering by the Tag?

**Comment by aadamovich** [comment] 2018-06-28 22:59
Duplicate of #19

**Closed by aadamovich** 2018-06-28 22:59 UTC
